<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-LOEDF30" failures="1" tests="1" name="Test(failed)" time="0.037" errors="0" timestamp="2024-08-17T04:12:59 EEST">
  <testcase classname="junit_testng.TestNG" name="test3" time="0.007">
    <failure type="java.lang.AssertionError" message="[ERROR] TestCase is failed  expected [hello] but found [hello1]">
      <![CDATA[java.lang.AssertionError: [ERROR] TestCase is failed  expected [hello] but found [hello1]
at junit_testng.TestNG.test3(TestNG.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="junit_testng.TestNG" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="junit_testng.TestNG" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
